version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-decor-house-prod
    restart: always
    environment:
      MYSQL_DATABASE: decor_house_prod
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - '3309:3306'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-padmin123" ]
      timeout: 20s
      retries: 10
      start_period: 40s
    networks:
      - backend

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: decor-house-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8084:8084'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/decor_house_prod?useSSL=false&serverTimezone=America/Lima
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    restart: unless-stopped
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: decor_house_net
